package clob

const (
	timeEndpoint = "/time"

	initialCursor = "MA=="
	endCursor     = "LTE="

	createAPIKeyEndpoint           = "/auth/api-key"
	getAPIKeysEndpoint             = "/auth/api-keys"
	deleteAPIKeyEndpoint           = "/auth/api-key"
	deriveAPIKeyEndpoint           = "/auth/derive-api-key"
	createBuilderAPIKeyEndpoint    = "/auth/builder-api-key"
	getBuilderAPIKeysEndpoint      = "/auth/builder-api-key"
	revokeBuilderAPIKeyEndpoint    = "/auth/builder-api-key"
	closedOnlyEndpoint             = "/auth/ban-status/closed-only"
	createReadonlyAPIKeyEndpoint   = "/auth/readonly-api-key"
	getReadonlyAPIKeysEndpoint     = "/auth/readonly-api-keys"
	deleteReadonlyAPIKeyEndpoint   = "/auth/readonly-api-key"
	validateReadonlyAPIKeyEndpoint = "/auth/validate-readonly-api-key"

	samplingSimplifiedMarketsEndpoint = "/sampling-simplified-markets"
	samplingMarketsEndpoint           = "/sampling-markets"
	simplifiedMarketsEndpoint         = "/simplified-markets"
	marketsEndpoint                   = "/markets"
	marketEndpoint                    = "/markets/"
	orderBookEndpoint                 = "/book"
	orderBooksEndpoint                = "/books"
	midpointEndpoint                  = "/midpoint"
	midpointsEndpoint                 = "/midpoints"
	priceEndpoint                     = "/price"
	pricesEndpoint                    = "/prices"
	spreadEndpoint                    = "/spread"
	spreadsEndpoint                   = "/spreads"
	lastTradePriceEndpoint            = "/last-trade-price"
	lastTradesPricesEndpoint          = "/last-trades-prices"
	tickSizeEndpoint                  = "/tick-size"
	negRiskEndpoint                   = "/neg-risk"
	feeRateEndpoint                   = "/fee-rate"
	priceHistoryEndpoint              = "/prices-history"
	marketTradesEventsEndpoint        = "/live-activity/events/"

	postOrderEndpoint              = "/order"
	postOrdersEndpoint             = "/orders"
	cancelOrderEndpoint            = "/order"
	cancelOrdersEndpoint           = "/orders"
	orderEndpoint                  = "/data/order/"
	cancelAllEndpoint              = "/cancel-all"
	cancelMarketOrdersEndpoint     = "/cancel-market-orders"
	openOrdersEndpoint             = "/data/orders"
	tradesEndpoint                 = "/data/trades"
	builderTradesEndpoint          = "/builder/trades"
	heartbeatEndpoint              = "/v1/heartbeats"
	notificationsEndpoint          = "/notifications"
	balanceAllowanceEndpoint       = "/balance-allowance"
	updateBalanceAllowanceEndpoint = "/balance-allowance/update"
	orderScoringEndpoint           = "/order-scoring"
	ordersScoringEndpoint          = "/orders-scoring"
	rewardsUserEndpoint            = "/rewards/user"
	rewardsUserTotalEndpoint       = "/rewards/user/total"
	rewardsPercentagesEndpoint     = "/rewards/user/percentages"
	rewardsUserMarketsEndpoint     = "/rewards/user/markets"
	rewardsMarketsCurrentEndpoint  = "/rewards/markets/current"
	rewardsMarketsEndpoint         = "/rewards/markets/"
)
